creating dataframe

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.random.random(size=(5, 3))
print(data)
df = pd.DataFrame(data=data, columns=["A","B","C"])
df

[[0.38519405 0.45286835 0.97853027]
 [0.25836113 0.97705941 0.21509407]
 [0.8616896  0.39440621 0.93609002]
 [0.1711948  0.77397385 0.02462699]
 [0.42333948 0.77686177 0.74327307]]


A         B         C
0  0.385194  0.452868  0.978530
1  0.258361  0.977059  0.215094
2  0.861690  0.394406  0.936090
3  0.171195  0.773974  0.024627
4  0.423339  0.776862  0.743273

In [3]:
# creating data frames using dictionaries
df = pd.DataFrame(data = {"A":[1,2,3], "B":["Sam", "Alex", "John"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [5]:
dtype = [("A", int),("B",(str, 20))]
data = np.array([(1,"Sam"), (2,"Alex"), (3,"John")], dtype=dtype)
df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John